### ISSUE TITLE
Add custom pvc for etcd disaster recovery

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-helm#20]
To support other `NFS provisioners` like amazons `EFS` some additional properties must be set in the `PVC` e.g. annotations. This is not supported by the `ETCD` chart. However it allows to set a custom `PCV` this can be part of the helm chart.

``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-snapshot-disaster-recovery
  namespace: weaviate
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: aws-efs
```

`etcd.disasterRecovery.pvc.existingClaim: etcd-snapshot-disaster-recovery`
